language: node_js
node_js:
- '5.11'
install:
- npm install
script:
- npm run build
- npm test
- npm run coveralls
deploy:
  provider: heroku
  skip_cleanup: true
  buildpack: nodejs
  api_key:
    secure: gvJm0PXHeKuUaXAG9xRpLeqUdbkIFqhuNh7F0vDqv0QUCrq90D5EivOKBJEj0+EOdWrTwxHK0IyztW/RJgttvczfguJgfozWF/hUgpmwK0ae4j9gy0hQas/2uo/bRl6R1QZLu42ENNdVplLec0jBh0wSaKv3YjYCqdBp9T6no5b7lxOBS218NHA/I5VBcwaNE12HmC2pdPuLq7f1d0C5GGF0yu7R9IqR4vZ1qF9nrvYSyXb7kumU1KauHgSMgy72rZWBKDPz2wplKYjg83rfPM3k12+32x2YRnC4fmt+DNGk96TPw27j+qy4nWTsWLCEf7XHIl9JBAqsnapNgfrwikPiTqKLzWnPyIIIKQYyzF9dN40eNSlRfqdAj3nYRq+GhjRBaWV0kTVu2g18+RtFUlrdzsoQWJIOIxB0Tw/eUxV1DRcouSg/II65oVMgxJoGbAmv4S5ngCSof20AmCCqacieJmTx/BKGbETDKx7q4nnZt47SbRNM7f2bXbE1OKEnAcSKucuutVVGraXJgA/s67EY4AuxB8cdxorIPQ84Co2atpeLX0IyTydjdci+tG5M1AvsWj72e3QE5HnxKVAe2GRM9m4pLCOubWVTkKO/5mzQkShtYVA5TsdWqw+KIBKUjEjgTz5qyAJMGE7yeAngctwpB1FsfHchwfD9p8Balr4=
  app: glo-ci-demo
  on:
    branch: master
    repo: GLO3112/ci-demo
